version: "3.8"

services:
  db:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongo --username ${MONGO_USER} --password ${MONGO_PASSWORD} --authenticationDatabase admin --eval 'db.runCommand({ ping: 1 })' localhost:27017"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  fastapi:
    build: .
    container_name: fastapi-container
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=db
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
    volumes:
      - .:/app
    restart: always
    command: >
      sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  mongo_data: